version: '2.26.1'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
